version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres-soporte
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: soporte
      SECRET_KEY: soporte_secret_key
  
  soporte:
    container_name: soporte-patrimonio
    image: soporte
    restart: always
    ports:
      - 8090:8080

# run: docker-compose -f docker-compose.yml up -d --buildl