version: '3.7'

services:
  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      #      DATABASE_HOST: 127.0.0.1
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventario
      POSTGRES_USER: postgres
    networks:
      - my-network

  pgadmin:
    container_name: pg-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - my-network

  node:
    container_name: back-container
    image: inventario-backend:1.8
    restart: always
    ports:
      - 3050:3050
    environment:
      - PGUSER=postgres
      - PGPASSWORD=admin
      - PGDATABASE=inventario
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
    external: true

# run: docker-compose -f docker-compose.yml up -d --build